version: "2"
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/web/nginx:/etc/nginx
    networks:
      - net
  backend:
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
    build:
      context: src/web/backend
    volumes:
      - ./src/web/backend:/app
    networks:
      - net
  frontend:
    build:
      context: src/web/frontend
    networks:
      - net
