version: "2"
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  backend:
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
    build:
      context: src/web/backend
    ports:
      - "127.0.0.1:8080:5000"
    volumes:
      - ./src/web/backend:/app
    networks:
      - net
  frontend:
    build:
      context: src/web/frontend
    ports:
      - "80:3000"
    volumes:
      - ./src/web/frontend:/app
    networks:
      - net
